---
version: 2
updates:
  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 10
    reviewers:
      - "spheric-cloud/core"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 10
    reviewers:
      - "spheric-cloud/core"
  - package-ecosystem: "pip"
    directory: "/docs"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 10
    reviewers:
      - "spheric-cloud/core"
  - package-ecosystem: "docker"
    directory: "/docs"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 10
    reviewers:
      - "spheric-cloud/core"
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 10
    reviewers:
      - "spheric-cloud/core"
