version: "2"
run:
  concurrency: 4
linters:
  enable:
    - ginkgolinter
    - importas
    - misspell
    - revive
  disable:
    - unused
  settings:
    importas:
      alias:
        - pkg: spheric.cloud/spheric/api/(\w+)/(v[\w\d]+)
          alias: $1$2
        - pkg: spheric.cloud/spheric/internal/apis/(\w+)
          alias: $1
        - pkg: spheric.cloud/spheric/internal/client/(\w+)
          alias: ${1}client
        - pkg: spheric.cloud/spheric/iri-api/apis/runtime/v1alpha1
          alias: iri
    misspell:
      ignore-rules:
        - strat
        - iritable
        - creater
        - Creater
    revive:
      severity: error
      rules:
        - name: exported
          arguments:
            - disableStutteringCheck
        - name: if-return
          disabled: true
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - path: (.+)\.go$
        text: 'exported: type name will be used as (.+) by other packages, and that stutters; consider calling this (.+)'
    paths:
      - third_party$
      - builtin$
      - examples$
severity:
  default: error
formatters:
  enable:
    - goimports
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
