// SPDX-FileCopyrightText: 2024 Axel Christ and Spheric contributors
// SPDX-License-Identifier: Apache-2.0

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package internal

import (
	"fmt"
	"sync"

	typed "sigs.k8s.io/structured-merge-diff/v4/typed"
)

func Parser() *typed.Parser {
	parserOnce.Do(func() {
		var err error
		parser, err = typed.NewParser(schemaYAML)
		if err != nil {
			panic(fmt.Sprintf("Failed to parse schema: %v", err))
		}
	})
	return parser
}

var parserOnce sync.Once
var parser *typed.Parser
var schemaYAML = typed.YAMLObject(`types:
- name: cloud.spheric.spheric.api.core.v1alpha1.AttachedDisk
  map:
    fields:
    - name: device
      type:
        scalar: string
    - name: diskRef
      type:
        namedType: cloud.spheric.spheric.api.core.v1alpha1.LocalObjectReference
    - name: emptyDisk
      type:
        namedType: cloud.spheric.spheric.api.core.v1alpha1.EmptyDiskSource
    - name: ephemeral
      type:
        namedType: cloud.spheric.spheric.api.core.v1alpha1.EphemeralDiskSource
    - name: name
      type:
        scalar: string
      default: ""
- name: cloud.spheric.spheric.api.core.v1alpha1.AttachedDiskStatus
  map:
    fields:
    - name: lastStateTransitionTime
      type:
        namedType: io.k8s.apimachinery.pkg.apis.meta.v1.Time
    - name: name
      type:
        scalar: string
      default: ""
    - name: state
      type:
        scalar: string
- name: cloud.spheric.spheric.api.core.v1alpha1.DaemonEndpoint
  map:
    fields:
    - name: port
      type:
        scalar: numeric
      default: 0
- name: cloud.spheric.spheric.api.core.v1alpha1.Disk
  map:
    fields:
    - name: apiVersion
      type:
        scalar: string
    - name: kind
      type:
        scalar: string
    - name: metadata
      type:
        namedType: io.k8s.apimachinery.pkg.apis.meta.v1.ObjectMeta
      default: {}
    - name: spec
      type:
        namedType: cloud.spheric.spheric.api.core.v1alpha1.DiskSpec
      default: {}
    - name: status
      type:
        namedType: cloud.spheric.spheric.api.core.v1alpha1.DiskStatus
      default: {}
- name: cloud.spheric.spheric.api.core.v1alpha1.DiskAccess
  map:
    fields:
    - name: attributes
      type:
        map:
          elementType:
            scalar: string
    - name: driver
      type:
        scalar: string
      default: ""
    - name: handle
      type:
        scalar: string
      default: ""
    - name: secretRef
      type:
        namedType: cloud.spheric.spheric.api.core.v1alpha1.LocalObjectReference
- name: cloud.spheric.spheric.api.core.v1alpha1.DiskSpec
  map:
    fields:
    - name: instanceRef
      type:
        namedType: cloud.spheric.spheric.api.core.v1alpha1.LocalUIDReference
    - name: resources
      type:
        map:
          elementType:
            namedType: io.k8s.apimachinery.pkg.api.resource.Quantity
    - name: typeRef
      type:
        namedType: cloud.spheric.spheric.api.core.v1alpha1.LocalObjectReference
      default: {}
- name: cloud.spheric.spheric.api.core.v1alpha1.DiskStatus
  map:
    fields:
    - name: access
      type:
        namedType: cloud.spheric.spheric.api.core.v1alpha1.DiskAccess
    - name: lastStateTransitionTime
      type:
        namedType: io.k8s.apimachinery.pkg.apis.meta.v1.Time
    - name: state
      type:
        scalar: string
- name: cloud.spheric.spheric.api.core.v1alpha1.DiskTemplateSpec
  map:
    fields:
    - name: metadata
      type:
        namedType: io.k8s.apimachinery.pkg.apis.meta.v1.ObjectMeta
      default: {}
    - name: spec
      type:
        namedType: cloud.spheric.spheric.api.core.v1alpha1.DiskSpec
      default: {}
- name: cloud.spheric.spheric.api.core.v1alpha1.DiskType
  map:
    fields:
    - name: apiVersion
      type:
        scalar: string
    - name: kind
      type:
        scalar: string
    - name: metadata
      type:
        namedType: io.k8s.apimachinery.pkg.apis.meta.v1.ObjectMeta
      default: {}
- name: cloud.spheric.spheric.api.core.v1alpha1.EFIVar
  map:
    fields:
    - name: name
      type:
        scalar: string
      default: ""
    - name: uuid
      type:
        scalar: string
      default: ""
    - name: value
      type:
        scalar: string
      default: ""
- name: cloud.spheric.spheric.api.core.v1alpha1.EmptyDiskSource
  map:
    fields:
    - name: sizeLimit
      type:
        namedType: io.k8s.apimachinery.pkg.api.resource.Quantity
- name: cloud.spheric.spheric.api.core.v1alpha1.EphemeralDiskSource
  map:
    fields:
    - name: diskTemplate
      type:
        namedType: cloud.spheric.spheric.api.core.v1alpha1.DiskTemplateSpec
- name: cloud.spheric.spheric.api.core.v1alpha1.Fleet
  map:
    fields:
    - name: apiVersion
      type:
        scalar: string
    - name: kind
      type:
        scalar: string
    - name: metadata
      type:
        namedType: io.k8s.apimachinery.pkg.apis.meta.v1.ObjectMeta
      default: {}
    - name: spec
      type:
        namedType: cloud.spheric.spheric.api.core.v1alpha1.FleetSpec
      default: {}
    - name: status
      type:
        namedType: cloud.spheric.spheric.api.core.v1alpha1.FleetStatus
      default: {}
- name: cloud.spheric.spheric.api.core.v1alpha1.FleetAddress
  map:
    fields:
    - name: address
      type:
        scalar: string
      default: ""
    - name: type
      type:
        scalar: string
      default: ""
- name: cloud.spheric.spheric.api.core.v1alpha1.FleetCondition
  map:
    fields:
    - name: lastTransitionTime
      type:
        namedType: io.k8s.apimachinery.pkg.apis.meta.v1.Time
    - name: message
      type:
        scalar: string
      default: ""
    - name: observedGeneration
      type:
        scalar: numeric
    - name: reason
      type:
        scalar: string
      default: ""
    - name: status
      type:
        scalar: string
      default: ""
    - name: type
      type:
        scalar: string
      default: ""
- name: cloud.spheric.spheric.api.core.v1alpha1.FleetDaemonEndpoints
  map:
    fields:
    - name: sphereletEndpoint
      type:
        namedType: cloud.spheric.spheric.api.core.v1alpha1.DaemonEndpoint
      default: {}
- name: cloud.spheric.spheric.api.core.v1alpha1.FleetSpec
  map:
    fields:
    - name: providerID
      type:
        scalar: string
      default: ""
    - name: taints
      type:
        list:
          elementType:
            namedType: cloud.spheric.spheric.api.core.v1alpha1.Taint
          elementRelationship: atomic
- name: cloud.spheric.spheric.api.core.v1alpha1.FleetStatus
  map:
    fields:
    - name: addresses
      type:
        list:
          elementType:
            namedType: cloud.spheric.spheric.api.core.v1alpha1.FleetAddress
          elementRelationship: atomic
    - name: allocatable
      type:
        map:
          elementType:
            namedType: io.k8s.apimachinery.pkg.api.resource.Quantity
    - name: capacity
      type:
        map:
          elementType:
            namedType: io.k8s.apimachinery.pkg.api.resource.Quantity
    - name: conditions
      type:
        list:
          elementType:
            namedType: cloud.spheric.spheric.api.core.v1alpha1.FleetCondition
          elementRelationship: atomic
    - name: daemonEndpoints
      type:
        namedType: cloud.spheric.spheric.api.core.v1alpha1.FleetDaemonEndpoints
      default: {}
    - name: state
      type:
        scalar: string
- name: cloud.spheric.spheric.api.core.v1alpha1.Instance
  map:
    fields:
    - name: apiVersion
      type:
        scalar: string
    - name: kind
      type:
        scalar: string
    - name: metadata
      type:
        namedType: io.k8s.apimachinery.pkg.apis.meta.v1.ObjectMeta
      default: {}
    - name: spec
      type:
        namedType: cloud.spheric.spheric.api.core.v1alpha1.InstanceSpec
      default: {}
    - name: status
      type:
        namedType: cloud.spheric.spheric.api.core.v1alpha1.InstanceStatus
      default: {}
- name: cloud.spheric.spheric.api.core.v1alpha1.InstanceSpec
  map:
    fields:
    - name: disks
      type:
        list:
          elementType:
            namedType: cloud.spheric.spheric.api.core.v1alpha1.AttachedDisk
          elementRelationship: associative
          keys:
          - name
    - name: efiVars
      type:
        list:
          elementType:
            namedType: cloud.spheric.spheric.api.core.v1alpha1.EFIVar
          elementRelationship: associative
          keys:
          - name
    - name: fleetRef
      type:
        namedType: cloud.spheric.spheric.api.core.v1alpha1.LocalObjectReference
    - name: fleetSelector
      type:
        map:
          elementType:
            scalar: string
    - name: ignitionRef
      type:
        namedType: cloud.spheric.spheric.api.core.v1alpha1.SecretKeySelector
    - name: image
      type:
        scalar: string
    - name: imagePullSecret
      type:
        namedType: cloud.spheric.spheric.api.core.v1alpha1.LocalObjectReference
    - name: instanceTypeRef
      type:
        namedType: cloud.spheric.spheric.api.core.v1alpha1.LocalObjectReference
      default: {}
    - name: networkInterfaces
      type:
        list:
          elementType:
            namedType: cloud.spheric.spheric.api.core.v1alpha1.NetworkInterface
          elementRelationship: associative
          keys:
          - name
    - name: power
      type:
        scalar: string
    - name: tolerations
      type:
        list:
          elementType:
            namedType: cloud.spheric.spheric.api.core.v1alpha1.Toleration
          elementRelationship: atomic
- name: cloud.spheric.spheric.api.core.v1alpha1.InstanceStatus
  map:
    fields:
    - name: disks
      type:
        list:
          elementType:
            namedType: cloud.spheric.spheric.api.core.v1alpha1.AttachedDiskStatus
          elementRelationship: atomic
    - name: instanceID
      type:
        scalar: string
    - name: networkInterfaces
      type:
        list:
          elementType:
            namedType: cloud.spheric.spheric.api.core.v1alpha1.NetworkInterfaceStatus
          elementRelationship: atomic
    - name: observedGeneration
      type:
        scalar: numeric
    - name: state
      type:
        scalar: string
- name: cloud.spheric.spheric.api.core.v1alpha1.InstanceType
  map:
    fields:
    - name: apiVersion
      type:
        scalar: string
    - name: capabilities
      type:
        map:
          elementType:
            namedType: io.k8s.apimachinery.pkg.api.resource.Quantity
    - name: class
      type:
        scalar: string
    - name: kind
      type:
        scalar: string
    - name: metadata
      type:
        namedType: io.k8s.apimachinery.pkg.apis.meta.v1.ObjectMeta
      default: {}
- name: cloud.spheric.spheric.api.core.v1alpha1.LocalObjectReference
  map:
    fields:
    - name: name
      type:
        scalar: string
- name: cloud.spheric.spheric.api.core.v1alpha1.LocalUIDReference
  map:
    fields:
    - name: name
      type:
        scalar: string
      default: ""
    - name: uid
      type:
        scalar: string
      default: ""
    elementRelationship: atomic
- name: cloud.spheric.spheric.api.core.v1alpha1.Network
  map:
    fields:
    - name: apiVersion
      type:
        scalar: string
    - name: kind
      type:
        scalar: string
    - name: metadata
      type:
        namedType: io.k8s.apimachinery.pkg.apis.meta.v1.ObjectMeta
      default: {}
    - name: spec
      type:
        namedType: cloud.spheric.spheric.api.core.v1alpha1.NetworkSpec
      default: {}
    - name: status
      type:
        namedType: cloud.spheric.spheric.api.core.v1alpha1.NetworkStatus
      default: {}
- name: cloud.spheric.spheric.api.core.v1alpha1.NetworkInterface
  map:
    fields:
    - name: accessIPFamilies
      type:
        list:
          elementType:
            scalar: string
          elementRelationship: atomic
    - name: accessIPs
      type:
        list:
          elementType:
            scalar: string
          elementRelationship: atomic
    - name: ipFamilies
      type:
        list:
          elementType:
            scalar: string
          elementRelationship: atomic
    - name: ips
      type:
        list:
          elementType:
            scalar: string
          elementRelationship: atomic
    - name: name
      type:
        scalar: string
      default: ""
    - name: subnetRef
      type:
        namedType: cloud.spheric.spheric.api.core.v1alpha1.SubnetReference
      default: {}
- name: cloud.spheric.spheric.api.core.v1alpha1.NetworkInterfaceStatus
  map:
    fields:
    - name: accessIPs
      type:
        list:
          elementType:
            scalar: string
          elementRelationship: atomic
    - name: ips
      type:
        list:
          elementType:
            scalar: string
          elementRelationship: atomic
    - name: lastStateTransitionTime
      type:
        namedType: io.k8s.apimachinery.pkg.apis.meta.v1.Time
    - name: name
      type:
        scalar: string
      default: ""
    - name: state
      type:
        scalar: string
- name: cloud.spheric.spheric.api.core.v1alpha1.NetworkSpec
  map:
    elementType:
      scalar: untyped
      list:
        elementType:
          namedType: __untyped_atomic_
        elementRelationship: atomic
      map:
        elementType:
          namedType: __untyped_deduced_
        elementRelationship: separable
- name: cloud.spheric.spheric.api.core.v1alpha1.NetworkStatus
  map:
    fields:
    - name: state
      type:
        scalar: string
- name: cloud.spheric.spheric.api.core.v1alpha1.SecretKeySelector
  map:
    fields:
    - name: key
      type:
        scalar: string
    - name: name
      type:
        scalar: string
    elementRelationship: atomic
- name: cloud.spheric.spheric.api.core.v1alpha1.Subnet
  map:
    fields:
    - name: apiVersion
      type:
        scalar: string
    - name: kind
      type:
        scalar: string
    - name: metadata
      type:
        namedType: io.k8s.apimachinery.pkg.apis.meta.v1.ObjectMeta
      default: {}
    - name: spec
      type:
        namedType: cloud.spheric.spheric.api.core.v1alpha1.SubnetSpec
      default: {}
    - name: status
      type:
        namedType: cloud.spheric.spheric.api.core.v1alpha1.SubnetStatus
      default: {}
- name: cloud.spheric.spheric.api.core.v1alpha1.SubnetReference
  map:
    fields:
    - name: name
      type:
        scalar: string
    - name: networkName
      type:
        scalar: string
- name: cloud.spheric.spheric.api.core.v1alpha1.SubnetSpec
  map:
    fields:
    - name: cidrs
      type:
        list:
          elementType:
            scalar: string
          elementRelationship: atomic
    - name: networkRef
      type:
        namedType: cloud.spheric.spheric.api.core.v1alpha1.LocalObjectReference
      default: {}
- name: cloud.spheric.spheric.api.core.v1alpha1.SubnetStatus
  map:
    fields:
    - name: state
      type:
        scalar: string
- name: cloud.spheric.spheric.api.core.v1alpha1.Taint
  map:
    fields:
    - name: effect
      type:
        scalar: string
      default: ""
    - name: key
      type:
        scalar: string
      default: ""
    - name: value
      type:
        scalar: string
- name: cloud.spheric.spheric.api.core.v1alpha1.Toleration
  map:
    fields:
    - name: effect
      type:
        scalar: string
    - name: key
      type:
        scalar: string
    - name: operator
      type:
        scalar: string
    - name: value
      type:
        scalar: string
- name: io.k8s.apimachinery.pkg.api.resource.Quantity
  scalar: untyped
- name: io.k8s.apimachinery.pkg.apis.meta.v1.FieldsV1
  map:
    elementType:
      scalar: untyped
      list:
        elementType:
          namedType: __untyped_atomic_
        elementRelationship: atomic
      map:
        elementType:
          namedType: __untyped_deduced_
        elementRelationship: separable
- name: io.k8s.apimachinery.pkg.apis.meta.v1.ManagedFieldsEntry
  map:
    fields:
    - name: apiVersion
      type:
        scalar: string
    - name: fieldsType
      type:
        scalar: string
    - name: fieldsV1
      type:
        namedType: io.k8s.apimachinery.pkg.apis.meta.v1.FieldsV1
    - name: manager
      type:
        scalar: string
    - name: operation
      type:
        scalar: string
    - name: subresource
      type:
        scalar: string
    - name: time
      type:
        namedType: io.k8s.apimachinery.pkg.apis.meta.v1.Time
- name: io.k8s.apimachinery.pkg.apis.meta.v1.ObjectMeta
  map:
    fields:
    - name: annotations
      type:
        map:
          elementType:
            scalar: string
    - name: creationTimestamp
      type:
        namedType: io.k8s.apimachinery.pkg.apis.meta.v1.Time
    - name: deletionGracePeriodSeconds
      type:
        scalar: numeric
    - name: deletionTimestamp
      type:
        namedType: io.k8s.apimachinery.pkg.apis.meta.v1.Time
    - name: finalizers
      type:
        list:
          elementType:
            scalar: string
          elementRelationship: associative
    - name: generateName
      type:
        scalar: string
    - name: generation
      type:
        scalar: numeric
    - name: labels
      type:
        map:
          elementType:
            scalar: string
    - name: managedFields
      type:
        list:
          elementType:
            namedType: io.k8s.apimachinery.pkg.apis.meta.v1.ManagedFieldsEntry
          elementRelationship: atomic
    - name: name
      type:
        scalar: string
    - name: namespace
      type:
        scalar: string
    - name: ownerReferences
      type:
        list:
          elementType:
            namedType: io.k8s.apimachinery.pkg.apis.meta.v1.OwnerReference
          elementRelationship: associative
          keys:
          - uid
    - name: resourceVersion
      type:
        scalar: string
    - name: selfLink
      type:
        scalar: string
    - name: uid
      type:
        scalar: string
- name: io.k8s.apimachinery.pkg.apis.meta.v1.OwnerReference
  map:
    fields:
    - name: apiVersion
      type:
        scalar: string
      default: ""
    - name: blockOwnerDeletion
      type:
        scalar: boolean
    - name: controller
      type:
        scalar: boolean
    - name: kind
      type:
        scalar: string
      default: ""
    - name: name
      type:
        scalar: string
      default: ""
    - name: uid
      type:
        scalar: string
      default: ""
    elementRelationship: atomic
- name: io.k8s.apimachinery.pkg.apis.meta.v1.Time
  scalar: untyped
- name: __untyped_atomic_
  scalar: untyped
  list:
    elementType:
      namedType: __untyped_atomic_
    elementRelationship: atomic
  map:
    elementType:
      namedType: __untyped_atomic_
    elementRelationship: atomic
- name: __untyped_deduced_
  scalar: untyped
  list:
    elementType:
      namedType: __untyped_atomic_
    elementRelationship: atomic
  map:
    elementType:
      namedType: __untyped_deduced_
    elementRelationship: separable
`)
