// SPDX-FileCopyrightText: 2024 Axel Christ and Spheric contributors
// SPDX-License-Identifier: Apache-2.0

// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

import (
	"k8s.io/apimachinery/pkg/labels"
	"k8s.io/client-go/listers"
	"k8s.io/client-go/tools/cache"
	v1alpha1 "spheric.cloud/spheric/api/core/v1alpha1"
)

// DiskTypeLister helps list DiskTypes.
// All objects returned here must be treated as read-only.
type DiskTypeLister interface {
	// List lists all DiskTypes in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*v1alpha1.DiskType, err error)
	// Get retrieves the DiskType from the index for a given name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*v1alpha1.DiskType, error)
	DiskTypeListerExpansion
}

// diskTypeLister implements the DiskTypeLister interface.
type diskTypeLister struct {
	listers.ResourceIndexer[*v1alpha1.DiskType]
}

// NewDiskTypeLister returns a new DiskTypeLister.
func NewDiskTypeLister(indexer cache.Indexer) DiskTypeLister {
	return &diskTypeLister{listers.New[*v1alpha1.DiskType](indexer, v1alpha1.Resource("disktype"))}
}
