// SPDX-FileCopyrightText: 2024 Axel Christ and Spheric contributors
// SPDX-License-Identifier: Apache-2.0

// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

import (
	"k8s.io/apimachinery/pkg/labels"
	"k8s.io/client-go/listers"
	"k8s.io/client-go/tools/cache"
	v1alpha1 "spheric.cloud/spheric/api/core/v1alpha1"
)

// FleetLister helps list Fleets.
// All objects returned here must be treated as read-only.
type FleetLister interface {
	// List lists all Fleets in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*v1alpha1.Fleet, err error)
	// Get retrieves the Fleet from the index for a given name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*v1alpha1.Fleet, error)
	FleetListerExpansion
}

// fleetLister implements the FleetLister interface.
type fleetLister struct {
	listers.ResourceIndexer[*v1alpha1.Fleet]
}

// NewFleetLister returns a new FleetLister.
func NewFleetLister(indexer cache.Indexer) FleetLister {
	return &fleetLister{listers.New[*v1alpha1.Fleet](indexer, v1alpha1.Resource("fleet"))}
}
