// SPDX-FileCopyrightText: 2024 Axel Christ and Spheric contributors
// SPDX-License-Identifier: Apache-2.0

// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

import (
	"k8s.io/apimachinery/pkg/labels"
	"k8s.io/client-go/listers"
	"k8s.io/client-go/tools/cache"
	v1alpha1 "spheric.cloud/spheric/api/core/v1alpha1"
)

// InstanceTypeLister helps list InstanceTypes.
// All objects returned here must be treated as read-only.
type InstanceTypeLister interface {
	// List lists all InstanceTypes in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*v1alpha1.InstanceType, err error)
	// Get retrieves the InstanceType from the index for a given name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*v1alpha1.InstanceType, error)
	InstanceTypeListerExpansion
}

// instanceTypeLister implements the InstanceTypeLister interface.
type instanceTypeLister struct {
	listers.ResourceIndexer[*v1alpha1.InstanceType]
}

// NewInstanceTypeLister returns a new InstanceTypeLister.
func NewInstanceTypeLister(indexer cache.Indexer) InstanceTypeLister {
	return &instanceTypeLister{listers.New[*v1alpha1.InstanceType](indexer, v1alpha1.Resource("instancetype"))}
}
