// SPDX-FileCopyrightText: 2024 Axel Christ and Spheric contributors
// SPDX-License-Identifier: Apache-2.0

// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	"context"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	gentype "k8s.io/client-go/gentype"
	v1alpha1 "spheric.cloud/spheric/api/core/v1alpha1"
	corev1alpha1 "spheric.cloud/spheric/client-go/applyconfigurations/core/v1alpha1"
	scheme "spheric.cloud/spheric/client-go/spheric/scheme"
)

// DisksGetter has a method to return a DiskInterface.
// A group's client should implement this interface.
type DisksGetter interface {
	Disks(namespace string) DiskInterface
}

// DiskInterface has methods to work with Disk resources.
type DiskInterface interface {
	Create(ctx context.Context, disk *v1alpha1.Disk, opts v1.CreateOptions) (*v1alpha1.Disk, error)
	Update(ctx context.Context, disk *v1alpha1.Disk, opts v1.UpdateOptions) (*v1alpha1.Disk, error)
	// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
	UpdateStatus(ctx context.Context, disk *v1alpha1.Disk, opts v1.UpdateOptions) (*v1alpha1.Disk, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*v1alpha1.Disk, error)
	List(ctx context.Context, opts v1.ListOptions) (*v1alpha1.DiskList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.Disk, err error)
	Apply(ctx context.Context, disk *corev1alpha1.DiskApplyConfiguration, opts v1.ApplyOptions) (result *v1alpha1.Disk, err error)
	// Add a +genclient:noStatus comment above the type to avoid generating ApplyStatus().
	ApplyStatus(ctx context.Context, disk *corev1alpha1.DiskApplyConfiguration, opts v1.ApplyOptions) (result *v1alpha1.Disk, err error)
	DiskExpansion
}

// disks implements DiskInterface
type disks struct {
	*gentype.ClientWithListAndApply[*v1alpha1.Disk, *v1alpha1.DiskList, *corev1alpha1.DiskApplyConfiguration]
}

// newDisks returns a Disks
func newDisks(c *CoreV1alpha1Client, namespace string) *disks {
	return &disks{
		gentype.NewClientWithListAndApply[*v1alpha1.Disk, *v1alpha1.DiskList, *corev1alpha1.DiskApplyConfiguration](
			"disks",
			c.RESTClient(),
			scheme.ParameterCodec,
			namespace,
			func() *v1alpha1.Disk { return &v1alpha1.Disk{} },
			func() *v1alpha1.DiskList { return &v1alpha1.DiskList{} }),
	}
}
