// SPDX-FileCopyrightText: 2024 Axel Christ and Spheric contributors
// SPDX-License-Identifier: Apache-2.0

// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	"context"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	gentype "k8s.io/client-go/gentype"
	v1alpha1 "spheric.cloud/spheric/api/core/v1alpha1"
	corev1alpha1 "spheric.cloud/spheric/client-go/applyconfigurations/core/v1alpha1"
	scheme "spheric.cloud/spheric/client-go/spheric/scheme"
)

// SubnetsGetter has a method to return a SubnetInterface.
// A group's client should implement this interface.
type SubnetsGetter interface {
	Subnets(namespace string) SubnetInterface
}

// SubnetInterface has methods to work with Subnet resources.
type SubnetInterface interface {
	Create(ctx context.Context, subnet *v1alpha1.Subnet, opts v1.CreateOptions) (*v1alpha1.Subnet, error)
	Update(ctx context.Context, subnet *v1alpha1.Subnet, opts v1.UpdateOptions) (*v1alpha1.Subnet, error)
	// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
	UpdateStatus(ctx context.Context, subnet *v1alpha1.Subnet, opts v1.UpdateOptions) (*v1alpha1.Subnet, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*v1alpha1.Subnet, error)
	List(ctx context.Context, opts v1.ListOptions) (*v1alpha1.SubnetList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.Subnet, err error)
	Apply(ctx context.Context, subnet *corev1alpha1.SubnetApplyConfiguration, opts v1.ApplyOptions) (result *v1alpha1.Subnet, err error)
	// Add a +genclient:noStatus comment above the type to avoid generating ApplyStatus().
	ApplyStatus(ctx context.Context, subnet *corev1alpha1.SubnetApplyConfiguration, opts v1.ApplyOptions) (result *v1alpha1.Subnet, err error)
	SubnetExpansion
}

// subnets implements SubnetInterface
type subnets struct {
	*gentype.ClientWithListAndApply[*v1alpha1.Subnet, *v1alpha1.SubnetList, *corev1alpha1.SubnetApplyConfiguration]
}

// newSubnets returns a Subnets
func newSubnets(c *CoreV1alpha1Client, namespace string) *subnets {
	return &subnets{
		gentype.NewClientWithListAndApply[*v1alpha1.Subnet, *v1alpha1.SubnetList, *corev1alpha1.SubnetApplyConfiguration](
			"subnets",
			c.RESTClient(),
			scheme.ParameterCodec,
			namespace,
			func() *v1alpha1.Subnet { return &v1alpha1.Subnet{} },
			func() *v1alpha1.SubnetList { return &v1alpha1.SubnetList{} }),
	}
}
