apiVersion: compute.spheric.cloud/v1alpha1
kind: Machine
metadata:
  name: machine-sample
spec:
  machineClassRef:
    name: instancetype-sample
  #  machinePoolRef:
  #    name: default
  image: my-image
  volumes:
    - name: rootdisk # first disk is root disk
      # priority: 0 # optional
      volumeRef:
        name: my-disk
  ignitionRef:
    name: my-ignition-secret
