apiVersion: networking.spheric.cloud/v1alpha1
kind: NetworkInterface
metadata:
  name: networkinterface-sample
spec:
  networkRef:
    name: network-sample
  ipFamilies: [ IPv4 ]
#status:
#  ips: # This will be updated with the allocated addresses.
#    - 10.0.0.1
#    - 2607:f0d0:1002:51::4
