// SPDX-FileCopyrightText: 2024 Axel Christ and Spheric contributors
// SPDX-License-Identifier: Apache-2.0

// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

type MachineExpansion interface{}

type MachineClassExpansion interface{}

type MachinePoolExpansion interface{}
