---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: broker-role
rules:
- apiGroups:
  - compute.spheric.cloud
  resources:
  - machineclasses
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - compute.spheric.cloud
  resources:
  - machinepools
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - compute.spheric.cloud
  resources:
  - machinepools/proxy
  verbs:
  - get
  - create
