---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: broker-role
rules:
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - compute.spheric.cloud
  resources:
  - machines
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - compute.spheric.cloud
  resources:
  - machines/exec
  verbs:
  - create
  - get
- apiGroups:
  - networking.spheric.cloud
  resources:
  - loadbalancerroutings
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - networking.spheric.cloud
  resources:
  - loadbalancers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - networking.spheric.cloud
  resources:
  - loadbalancers/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - networking.spheric.cloud
  resources:
  - natgateways
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - networking.spheric.cloud
  resources:
  - natgateways/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - networking.spheric.cloud
  resources:
  - networkinterfaces
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - networking.spheric.cloud
  resources:
  - networks
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - networking.spheric.cloud
  resources:
  - networks/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - networking.spheric.cloud
  resources:
  - virtualips
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - networking.spheric.cloud
  resources:
  - virtualips/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - storage.spheric.cloud
  resources:
  - volumes
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - storage.spheric.cloud
  resources:
  - volumes/status
  verbs:
  - get
  - patch
  - update
