---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - patch
- apiGroups:
  - authorization.k8s.io
  resources:
  - subjectaccessreviews
  verbs:
  - create
- apiGroups:
  - certificates.k8s.io
  resources:
  - certificatesigningrequests
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - certificates.k8s.io
  resources:
  - certificatesigningrequests/approval
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - certificates.k8s.io
  resourceNames:
  - kubernetes.io/kube-apiserver-client
  resources:
  - signers
  verbs:
  - approve
- apiGroups:
  - core.spheric.cloud
  resources:
  - disks
  - instancetypes
  - networks
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - core.spheric.cloud
  resources:
  - fleets
  - loadbalancers
  - natgateways
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - core.spheric.cloud
  resources:
  - instances
  verbs:
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - core.spheric.cloud
  resources:
  - instances/status
  - instancetypes/status
  - networks/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - core.spheric.cloud
  resources:
  - instancetypes/finalizers
  - networks/finalizers
  verbs:
  - update
