---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - patch
- apiGroups:
  - ""
  resources:
  - namespaces
  verbs:
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - authorization.k8s.io
  resources:
  - subjectaccessreviews
  verbs:
  - create
- apiGroups:
  - certificates.k8s.io
  resources:
  - certificatesigningrequests
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - certificates.k8s.io
  resources:
  - certificatesigningrequests/approval
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - certificates.k8s.io
  resourceNames:
  - kubernetes.io/kube-apiserver-client
  resources:
  - signers
  verbs:
  - approve
- apiGroups:
  - compute.spheric.cloud
  resources:
  - machineclasses
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - compute.spheric.cloud
  resources:
  - machineclasses/finalizers
  verbs:
  - update
- apiGroups:
  - compute.spheric.cloud
  resources:
  - machineclasses/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - compute.spheric.cloud
  resources:
  - machinepools
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - compute.spheric.cloud
  resources:
  - machines
  verbs:
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - compute.spheric.cloud
  resources:
  - machines/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - core.spheric.cloud
  resources:
  - resourcequotas
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - core.spheric.cloud
  resources:
  - resourcequotas/finalizers
  verbs:
  - update
- apiGroups:
  - core.spheric.cloud
  resources:
  - resourcequotas/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - ipam.spheric.cloud
  resources:
  - prefixallocations
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ipam.spheric.cloud
  resources:
  - prefixallocations/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - ipam.spheric.cloud
  resources:
  - prefixes
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ipam.spheric.cloud
  resources:
  - prefixes/finalizers
  verbs:
  - update
- apiGroups:
  - ipam.spheric.cloud
  resources:
  - prefixes/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - networking.spheric.cloud
  resources:
  - loadbalancerroutings
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - networking.spheric.cloud
  resources:
  - loadbalancers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - networking.spheric.cloud
  resources:
  - loadbalancers/finalizers
  verbs:
  - update
- apiGroups:
  - networking.spheric.cloud
  resources:
  - loadbalancers/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - networking.spheric.cloud
  resources:
  - natgateways
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - networking.spheric.cloud
  resources:
  - networkinterfaces
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - networking.spheric.cloud
  resources:
  - networks
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - networking.spheric.cloud
  resources:
  - networks/finalizers
  verbs:
  - update
- apiGroups:
  - networking.spheric.cloud
  resources:
  - networks/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - networking.spheric.cloud
  resources:
  - virtualips
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - storage.spheric.cloud
  resources:
  - bucketclasses
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - storage.spheric.cloud
  resources:
  - bucketclasses/finalizers
  verbs:
  - update
- apiGroups:
  - storage.spheric.cloud
  resources:
  - bucketclasses/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - storage.spheric.cloud
  resources:
  - bucketpools
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - storage.spheric.cloud
  resources:
  - buckets
  verbs:
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - storage.spheric.cloud
  resources:
  - buckets/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - storage.spheric.cloud
  resources:
  - volumeclasses
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - storage.spheric.cloud
  resources:
  - volumeclasses/finalizers
  verbs:
  - update
- apiGroups:
  - storage.spheric.cloud
  resources:
  - volumeclasses/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - storage.spheric.cloud
  resources:
  - volumepools
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - storage.spheric.cloud
  resources:
  - volumes
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - storage.spheric.cloud
  resources:
  - volumes/status
  verbs:
  - get
  - patch
  - update
