# permissions for end users to view volumeclasses.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: volumeclass-viewer-role
rules:
  - apiGroups:
      - storage.spheric.cloud
    resources:
      - volumeclasses
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - storage.spheric.cloud
    resources:
      - volumeclasses/status
    verbs:
      - get
