// SPDX-FileCopyrightText: 2024 Axel Christ and Spheric contributors
// SPDX-License-Identifier: Apache-2.0

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

// AttachedDiskApplyConfiguration represents an declarative configuration of the AttachedDisk type for use
// with apply.
type AttachedDiskApplyConfiguration struct {
	Name                                 *string `json:"name,omitempty"`
	Device                               *string `json:"device,omitempty"`
	AttachedDiskSourceApplyConfiguration `json:",inline"`
}

// AttachedDiskApplyConfiguration constructs an declarative configuration of the AttachedDisk type for use with
// apply.
func AttachedDisk() *AttachedDiskApplyConfiguration {
	return &AttachedDiskApplyConfiguration{}
}

// WithName sets the Name field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Name field is set to the value of the last call.
func (b *AttachedDiskApplyConfiguration) WithName(value string) *AttachedDiskApplyConfiguration {
	b.Name = &value
	return b
}

// WithDevice sets the Device field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Device field is set to the value of the last call.
func (b *AttachedDiskApplyConfiguration) WithDevice(value string) *AttachedDiskApplyConfiguration {
	b.Device = &value
	return b
}

// WithDiskRef sets the DiskRef field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the DiskRef field is set to the value of the last call.
func (b *AttachedDiskApplyConfiguration) WithDiskRef(value *LocalObjectReferenceApplyConfiguration) *AttachedDiskApplyConfiguration {
	b.DiskRef = value
	return b
}

// WithEmptyDisk sets the EmptyDisk field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the EmptyDisk field is set to the value of the last call.
func (b *AttachedDiskApplyConfiguration) WithEmptyDisk(value *EmptyDiskSourceApplyConfiguration) *AttachedDiskApplyConfiguration {
	b.EmptyDisk = value
	return b
}

// WithEphemeral sets the Ephemeral field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Ephemeral field is set to the value of the last call.
func (b *AttachedDiskApplyConfiguration) WithEphemeral(value *EphemeralDiskSourceApplyConfiguration) *AttachedDiskApplyConfiguration {
	b.Ephemeral = value
	return b
}
