// SPDX-FileCopyrightText: 2024 Axel Christ and Spheric contributors
// SPDX-License-Identifier: Apache-2.0

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

import (
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	v1alpha1 "spheric.cloud/spheric/api/core/v1alpha1"
)

// AttachedDiskStatusApplyConfiguration represents a declarative configuration of the AttachedDiskStatus type for use
// with apply.
type AttachedDiskStatusApplyConfiguration struct {
	Name                    *string                     `json:"name,omitempty"`
	State                   *v1alpha1.AttachedDiskState `json:"state,omitempty"`
	LastStateTransitionTime *v1.Time                    `json:"lastStateTransitionTime,omitempty"`
}

// AttachedDiskStatusApplyConfiguration constructs a declarative configuration of the AttachedDiskStatus type for use with
// apply.
func AttachedDiskStatus() *AttachedDiskStatusApplyConfiguration {
	return &AttachedDiskStatusApplyConfiguration{}
}

// WithName sets the Name field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Name field is set to the value of the last call.
func (b *AttachedDiskStatusApplyConfiguration) WithName(value string) *AttachedDiskStatusApplyConfiguration {
	b.Name = &value
	return b
}

// WithState sets the State field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the State field is set to the value of the last call.
func (b *AttachedDiskStatusApplyConfiguration) WithState(value v1alpha1.AttachedDiskState) *AttachedDiskStatusApplyConfiguration {
	b.State = &value
	return b
}

// WithLastStateTransitionTime sets the LastStateTransitionTime field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the LastStateTransitionTime field is set to the value of the last call.
func (b *AttachedDiskStatusApplyConfiguration) WithLastStateTransitionTime(value v1.Time) *AttachedDiskStatusApplyConfiguration {
	b.LastStateTransitionTime = &value
	return b
}
