// SPDX-FileCopyrightText: 2024 Axel Christ and Spheric contributors
// SPDX-License-Identifier: Apache-2.0

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

// AttachedDiskSourceApplyConfiguration represents an declarative configuration of the AttachedDiskSource type for use
// with apply.
type AttachedDiskSourceApplyConfiguration struct {
	DiskRef   *LocalObjectReferenceApplyConfiguration `json:"diskRef,omitempty"`
	EmptyDisk *EmptyDiskSourceApplyConfiguration      `json:"emptyDisk,omitempty"`
	Ephemeral *EphemeralDiskSourceApplyConfiguration  `json:"ephemeral,omitempty"`
}

// AttachedDiskSourceApplyConfiguration constructs an declarative configuration of the AttachedDiskSource type for use with
// apply.
func AttachedDiskSource() *AttachedDiskSourceApplyConfiguration {
	return &AttachedDiskSourceApplyConfiguration{}
}

// WithDiskRef sets the DiskRef field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the DiskRef field is set to the value of the last call.
func (b *AttachedDiskSourceApplyConfiguration) WithDiskRef(value *LocalObjectReferenceApplyConfiguration) *AttachedDiskSourceApplyConfiguration {
	b.DiskRef = value
	return b
}

// WithEmptyDisk sets the EmptyDisk field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the EmptyDisk field is set to the value of the last call.
func (b *AttachedDiskSourceApplyConfiguration) WithEmptyDisk(value *EmptyDiskSourceApplyConfiguration) *AttachedDiskSourceApplyConfiguration {
	b.EmptyDisk = value
	return b
}

// WithEphemeral sets the Ephemeral field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Ephemeral field is set to the value of the last call.
func (b *AttachedDiskSourceApplyConfiguration) WithEphemeral(value *EphemeralDiskSourceApplyConfiguration) *AttachedDiskSourceApplyConfiguration {
	b.Ephemeral = value
	return b
}
