// SPDX-FileCopyrightText: 2024 Axel Christ and Spheric contributors
// SPDX-License-Identifier: Apache-2.0

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

// EphemeralDiskSourceApplyConfiguration represents an declarative configuration of the EphemeralDiskSource type for use
// with apply.
type EphemeralDiskSourceApplyConfiguration struct {
	DiskTemplate *DiskTemplateSpecApplyConfiguration `json:"diskTemplate,omitempty"`
}

// EphemeralDiskSourceApplyConfiguration constructs an declarative configuration of the EphemeralDiskSource type for use with
// apply.
func EphemeralDiskSource() *EphemeralDiskSourceApplyConfiguration {
	return &EphemeralDiskSourceApplyConfiguration{}
}

// WithDiskTemplate sets the DiskTemplate field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the DiskTemplate field is set to the value of the last call.
func (b *EphemeralDiskSourceApplyConfiguration) WithDiskTemplate(value *DiskTemplateSpecApplyConfiguration) *EphemeralDiskSourceApplyConfiguration {
	b.DiskTemplate = value
	return b
}
