// SPDX-FileCopyrightText: 2024 Axel Christ and Spheric contributors
// SPDX-License-Identifier: Apache-2.0

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

// FleetDaemonEndpointsApplyConfiguration represents a declarative configuration of the FleetDaemonEndpoints type for use
// with apply.
type FleetDaemonEndpointsApplyConfiguration struct {
	SphereletEndpoint *DaemonEndpointApplyConfiguration `json:"sphereletEndpoint,omitempty"`
}

// FleetDaemonEndpointsApplyConfiguration constructs a declarative configuration of the FleetDaemonEndpoints type for use with
// apply.
func FleetDaemonEndpoints() *FleetDaemonEndpointsApplyConfiguration {
	return &FleetDaemonEndpointsApplyConfiguration{}
}

// WithSphereletEndpoint sets the SphereletEndpoint field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the SphereletEndpoint field is set to the value of the last call.
func (b *FleetDaemonEndpointsApplyConfiguration) WithSphereletEndpoint(value *DaemonEndpointApplyConfiguration) *FleetDaemonEndpointsApplyConfiguration {
	b.SphereletEndpoint = value
	return b
}
