// SPDX-FileCopyrightText: 2024 Axel Christ and Spheric contributors
// SPDX-License-Identifier: Apache-2.0

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

// SubnetReferenceApplyConfiguration represents an declarative configuration of the SubnetReference type for use
// with apply.
type SubnetReferenceApplyConfiguration struct {
	NetworkName *string `json:"networkName,omitempty"`
	Name        *string `json:"name,omitempty"`
}

// SubnetReferenceApplyConfiguration constructs an declarative configuration of the SubnetReference type for use with
// apply.
func SubnetReference() *SubnetReferenceApplyConfiguration {
	return &SubnetReferenceApplyConfiguration{}
}

// WithNetworkName sets the NetworkName field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the NetworkName field is set to the value of the last call.
func (b *SubnetReferenceApplyConfiguration) WithNetworkName(value string) *SubnetReferenceApplyConfiguration {
	b.NetworkName = &value
	return b
}

// WithName sets the Name field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Name field is set to the value of the last call.
func (b *SubnetReferenceApplyConfiguration) WithName(value string) *SubnetReferenceApplyConfiguration {
	b.Name = &value
	return b
}
