apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: spheric-system
  name: spheric-controller-manager
spec:
  template:
    spec:
      containers:
        - name: manager
          imagePullPolicy: Never
