- op: add
  path: /spec/template/spec/containers/0/args/-
  value: --disk-pool-name=broker
- op: add
  path: /spec/template/spec/containers/0/args/-
  value: --provider-id=broker
- op: add
  path: /spec/template/spec/containers/0/args/-
  value: --provider-id=broker
- op: add
  path: /spec/template/spec/containers/1/args
  value:
    - --namespace=volumepoollet-system
    - --disk-pool-name=virtual
