---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: compute.spheric.cloud:system:machinepools
rules:
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - patch
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - create
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - authentication.k8s.io
  resources:
  - tokenreviews
  verbs:
  - create
- apiGroups:
  - authorization.k8s.io
  resources:
  - subjectaccessreviews
  verbs:
  - create
- apiGroups:
  - certificates.k8s.io
  resources:
  - certificatesigningrequests
  verbs:
  - create
  - get
  - list
  - watch
- apiGroups:
  - certificates.k8s.io
  resources:
  - certificatesigningrequests/machinepoolclient
  verbs:
  - create
- apiGroups:
  - compute.spheric.cloud
  resources:
  - machineclasses
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - compute.spheric.cloud
  resources:
  - machinepools
  verbs:
  - create
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - compute.spheric.cloud
  resources:
  - machinepools/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - compute.spheric.cloud
  resources:
  - machines
  verbs:
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - compute.spheric.cloud
  resources:
  - machines/finalizers
  verbs:
  - update
- apiGroups:
  - compute.spheric.cloud
  resources:
  - machines/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - ipam.spheric.cloud
  resources:
  - prefixes
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - networking.spheric.cloud
  resources:
  - networkinterfaces
  verbs:
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - networking.spheric.cloud
  resources:
  - networks
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - storage.spheric.cloud
  resources:
  - volumes
  verbs:
  - get
  - list
  - patch
  - update
  - watch
