---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: networking.spheric.cloud:system:networkplugins
rules:
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - patch
- apiGroups:
  - networking.spheric.cloud
  resources:
  - loadbalancers
  verbs:
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - networking.spheric.cloud
  resources:
  - loadbalancers/finalizers
  verbs:
  - patch
  - update
- apiGroups:
  - networking.spheric.cloud
  resources:
  - loadbalancers/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - networking.spheric.cloud
  resources:
  - natgateways
  verbs:
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - networking.spheric.cloud
  resources:
  - natgateways/finalizers
  verbs:
  - patch
  - update
- apiGroups:
  - networking.spheric.cloud
  resources:
  - natgateways/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - networking.spheric.cloud
  resources:
  - networks
  verbs:
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - networking.spheric.cloud
  resources:
  - networks/finalizers
  verbs:
  - patch
  - update
- apiGroups:
  - networking.spheric.cloud
  resources:
  - networks/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - networking.spheric.cloud
  resources:
  - virtualips
  verbs:
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - networking.spheric.cloud
  resources:
  - virtualips/finalizers
  verbs:
  - patch
  - update
- apiGroups:
  - networking.spheric.cloud
  resources:
  - virtualips/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - certificates.k8s.io
  resources:
  - certificatesigningrequests
  verbs:
  - create
  - get
  - list
  - watch
- apiGroups:
  - certificates.k8s.io
  resources:
  - certificatesigningrequests/networkpluginclient
  verbs:
  - create
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - create
  - get
  - list
  - patch
  - update
  - watch
