---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: storage.spheric.cloud:system:volumepools
rules:
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - patch
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - create
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - certificates.k8s.io
  resources:
  - certificatesigningrequests
  verbs:
  - create
  - get
  - list
  - watch
- apiGroups:
  - certificates.k8s.io
  resources:
  - certificatesigningrequests/volumepoolclient
  verbs:
  - create
- apiGroups:
  - storage.spheric.cloud
  resources:
  - volumeclasses
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - storage.spheric.cloud
  resources:
  - volumepools
  verbs:
  - create
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - storage.spheric.cloud
  resources:
  - volumepools/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - storage.spheric.cloud
  resources:
  - volumes
  verbs:
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - storage.spheric.cloud
  resources:
  - volumes/finalizers
  verbs:
  - update
- apiGroups:
  - storage.spheric.cloud
  resources:
  - volumes/status
  verbs:
  - get
  - patch
  - update
