// SPDX-FileCopyrightText: 2024 Axel Christ and Spheric contributors
// SPDX-License-Identifier: Apache-2.0

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

import (
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	commonv1alpha1 "spheric.cloud/spheric/api/common/v1alpha1"
	v1alpha1 "spheric.cloud/spheric/api/ipam/v1alpha1"
)

// PrefixStatusApplyConfiguration represents an declarative configuration of the PrefixStatus type for use
// with apply.
type PrefixStatusApplyConfiguration struct {
	Phase                   *v1alpha1.PrefixPhase     `json:"phase,omitempty"`
	LastPhaseTransitionTime *v1.Time                  `json:"lastPhaseTransitionTime,omitempty"`
	Used                    []commonv1alpha1.IPPrefix `json:"used,omitempty"`
}

// PrefixStatusApplyConfiguration constructs an declarative configuration of the PrefixStatus type for use with
// apply.
func PrefixStatus() *PrefixStatusApplyConfiguration {
	return &PrefixStatusApplyConfiguration{}
}

// WithPhase sets the Phase field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Phase field is set to the value of the last call.
func (b *PrefixStatusApplyConfiguration) WithPhase(value v1alpha1.PrefixPhase) *PrefixStatusApplyConfiguration {
	b.Phase = &value
	return b
}

// WithLastPhaseTransitionTime sets the LastPhaseTransitionTime field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the LastPhaseTransitionTime field is set to the value of the last call.
func (b *PrefixStatusApplyConfiguration) WithLastPhaseTransitionTime(value v1.Time) *PrefixStatusApplyConfiguration {
	b.LastPhaseTransitionTime = &value
	return b
}

// WithUsed adds the given value to the Used field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Used field.
func (b *PrefixStatusApplyConfiguration) WithUsed(values ...commonv1alpha1.IPPrefix) *PrefixStatusApplyConfiguration {
	for i := range values {
		b.Used = append(b.Used, values[i])
	}
	return b
}
