// SPDX-FileCopyrightText: 2024 Axel Christ and Spheric contributors
// SPDX-License-Identifier: Apache-2.0

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"
	json "encoding/json"
	"fmt"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
	v1alpha1 "spheric.cloud/spheric/api/core/v1alpha1"
	corev1alpha1 "spheric.cloud/spheric/client-go/applyconfigurations/core/v1alpha1"
)

// FakeDisks implements DiskInterface
type FakeDisks struct {
	Fake *FakeCoreV1alpha1
	ns   string
}

var disksResource = v1alpha1.SchemeGroupVersion.WithResource("disks")

var disksKind = v1alpha1.SchemeGroupVersion.WithKind("Disk")

// Get takes name of the disk, and returns the corresponding disk object, and an error if there is any.
func (c *FakeDisks) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.Disk, err error) {
	emptyResult := &v1alpha1.Disk{}
	obj, err := c.Fake.
		Invokes(testing.NewGetActionWithOptions(disksResource, c.ns, name, options), emptyResult)

	if obj == nil {
		return emptyResult, err
	}
	return obj.(*v1alpha1.Disk), err
}

// List takes label and field selectors, and returns the list of Disks that match those selectors.
func (c *FakeDisks) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.DiskList, err error) {
	emptyResult := &v1alpha1.DiskList{}
	obj, err := c.Fake.
		Invokes(testing.NewListActionWithOptions(disksResource, disksKind, c.ns, opts), emptyResult)

	if obj == nil {
		return emptyResult, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.DiskList{ListMeta: obj.(*v1alpha1.DiskList).ListMeta}
	for _, item := range obj.(*v1alpha1.DiskList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested disks.
func (c *FakeDisks) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchActionWithOptions(disksResource, c.ns, opts))

}

// Create takes the representation of a disk and creates it.  Returns the server's representation of the disk, and an error, if there is any.
func (c *FakeDisks) Create(ctx context.Context, disk *v1alpha1.Disk, opts v1.CreateOptions) (result *v1alpha1.Disk, err error) {
	emptyResult := &v1alpha1.Disk{}
	obj, err := c.Fake.
		Invokes(testing.NewCreateActionWithOptions(disksResource, c.ns, disk, opts), emptyResult)

	if obj == nil {
		return emptyResult, err
	}
	return obj.(*v1alpha1.Disk), err
}

// Update takes the representation of a disk and updates it. Returns the server's representation of the disk, and an error, if there is any.
func (c *FakeDisks) Update(ctx context.Context, disk *v1alpha1.Disk, opts v1.UpdateOptions) (result *v1alpha1.Disk, err error) {
	emptyResult := &v1alpha1.Disk{}
	obj, err := c.Fake.
		Invokes(testing.NewUpdateActionWithOptions(disksResource, c.ns, disk, opts), emptyResult)

	if obj == nil {
		return emptyResult, err
	}
	return obj.(*v1alpha1.Disk), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeDisks) UpdateStatus(ctx context.Context, disk *v1alpha1.Disk, opts v1.UpdateOptions) (result *v1alpha1.Disk, err error) {
	emptyResult := &v1alpha1.Disk{}
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceActionWithOptions(disksResource, "status", c.ns, disk, opts), emptyResult)

	if obj == nil {
		return emptyResult, err
	}
	return obj.(*v1alpha1.Disk), err
}

// Delete takes name of the disk and deletes it. Returns an error if one occurs.
func (c *FakeDisks) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteActionWithOptions(disksResource, c.ns, name, opts), &v1alpha1.Disk{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeDisks) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionActionWithOptions(disksResource, c.ns, opts, listOpts)

	_, err := c.Fake.Invokes(action, &v1alpha1.DiskList{})
	return err
}

// Patch applies the patch and returns the patched disk.
func (c *FakeDisks) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.Disk, err error) {
	emptyResult := &v1alpha1.Disk{}
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceActionWithOptions(disksResource, c.ns, name, pt, data, opts, subresources...), emptyResult)

	if obj == nil {
		return emptyResult, err
	}
	return obj.(*v1alpha1.Disk), err
}

// Apply takes the given apply declarative configuration, applies it and returns the applied disk.
func (c *FakeDisks) Apply(ctx context.Context, disk *corev1alpha1.DiskApplyConfiguration, opts v1.ApplyOptions) (result *v1alpha1.Disk, err error) {
	if disk == nil {
		return nil, fmt.Errorf("disk provided to Apply must not be nil")
	}
	data, err := json.Marshal(disk)
	if err != nil {
		return nil, err
	}
	name := disk.Name
	if name == nil {
		return nil, fmt.Errorf("disk.Name must be provided to Apply")
	}
	emptyResult := &v1alpha1.Disk{}
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceActionWithOptions(disksResource, c.ns, *name, types.ApplyPatchType, data, opts.ToPatchOptions()), emptyResult)

	if obj == nil {
		return emptyResult, err
	}
	return obj.(*v1alpha1.Disk), err
}

// ApplyStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating ApplyStatus().
func (c *FakeDisks) ApplyStatus(ctx context.Context, disk *corev1alpha1.DiskApplyConfiguration, opts v1.ApplyOptions) (result *v1alpha1.Disk, err error) {
	if disk == nil {
		return nil, fmt.Errorf("disk provided to Apply must not be nil")
	}
	data, err := json.Marshal(disk)
	if err != nil {
		return nil, err
	}
	name := disk.Name
	if name == nil {
		return nil, fmt.Errorf("disk.Name must be provided to Apply")
	}
	emptyResult := &v1alpha1.Disk{}
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceActionWithOptions(disksResource, c.ns, *name, types.ApplyPatchType, data, opts.ToPatchOptions(), "status"), emptyResult)

	if obj == nil {
		return emptyResult, err
	}
	return obj.(*v1alpha1.Disk), err
}
