// SPDX-FileCopyrightText: 2024 Axel Christ and Spheric contributors
// SPDX-License-Identifier: Apache-2.0

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	rest "k8s.io/client-go/rest"
	testing "k8s.io/client-go/testing"
	v1alpha1 "spheric.cloud/spheric/client-go/spheric/typed/core/v1alpha1"
)

type FakeCoreV1alpha1 struct {
	*testing.Fake
}

func (c *FakeCoreV1alpha1) Disks(namespace string) v1alpha1.DiskInterface {
	return &FakeDisks{c, namespace}
}

func (c *FakeCoreV1alpha1) DiskTypes() v1alpha1.DiskTypeInterface {
	return &FakeDiskTypes{c}
}

func (c *FakeCoreV1alpha1) Fleets() v1alpha1.FleetInterface {
	return &FakeFleets{c}
}

func (c *FakeCoreV1alpha1) Instances(namespace string) v1alpha1.InstanceInterface {
	return &FakeInstances{c, namespace}
}

func (c *FakeCoreV1alpha1) InstanceTypes() v1alpha1.InstanceTypeInterface {
	return &FakeInstanceTypes{c}
}

func (c *FakeCoreV1alpha1) Networks(namespace string) v1alpha1.NetworkInterface {
	return &FakeNetworks{c, namespace}
}

func (c *FakeCoreV1alpha1) Subnets(namespace string) v1alpha1.SubnetInterface {
	return &FakeSubnets{c, namespace}
}

// RESTClient returns a RESTClient that is used to communicate
// with API server by this client implementation.
func (c *FakeCoreV1alpha1) RESTClient() rest.Interface {
	var ret *rest.RESTClient
	return ret
}
