apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: spherelet-system
namePrefix: spherelet-

resources:
  - ../../poollet-rbac

patchesStrategicMerge:
  - delete_service_account.yaml
