// SPDX-FileCopyrightText: 2024 Axel Christ and Spheric contributors
// SPDX-License-Identifier: Apache-2.0

// Code generated by informer-gen. DO NOT EDIT.

package v1alpha1

import (
	"context"
	time "time"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
	corev1alpha1 "spheric.cloud/spheric/api/core/v1alpha1"
	internalinterfaces "spheric.cloud/spheric/client-go/informers/internalinterfaces"
	v1alpha1 "spheric.cloud/spheric/client-go/listers/core/v1alpha1"
	spheric "spheric.cloud/spheric/client-go/spheric"
)

// InstanceTypeInformer provides access to a shared informer and lister for
// InstanceTypes.
type InstanceTypeInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() v1alpha1.InstanceTypeLister
}

type instanceTypeInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
}

// NewInstanceTypeInformer constructs a new informer for InstanceType type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewInstanceTypeInformer(client spheric.Interface, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredInstanceTypeInformer(client, resyncPeriod, indexers, nil)
}

// NewFilteredInstanceTypeInformer constructs a new informer for InstanceType type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredInstanceTypeInformer(client spheric.Interface, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.CoreV1alpha1().InstanceTypes().List(context.TODO(), options)
			},
			WatchFunc: func(options v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.CoreV1alpha1().InstanceTypes().Watch(context.TODO(), options)
			},
		},
		&corev1alpha1.InstanceType{},
		resyncPeriod,
		indexers,
	)
}

func (f *instanceTypeInformer) defaultInformer(client spheric.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredInstanceTypeInformer(client, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *instanceTypeInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&corev1alpha1.InstanceType{}, f.defaultInformer)
}

func (f *instanceTypeInformer) Lister() v1alpha1.InstanceTypeLister {
	return v1alpha1.NewInstanceTypeLister(f.Informer().GetIndexer())
}
