// SPDX-FileCopyrightText: 2024 Axel Christ and Spheric contributors
// SPDX-License-Identifier: Apache-2.0

// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

type LoadBalancerExpansion interface{}

type LoadBalancerRoutingExpansion interface{}

type NATGatewayExpansion interface{}

type NetworkExpansion interface{}

type NetworkInterfaceExpansion interface{}

type NetworkPolicyExpansion interface{}

type VirtualIPExpansion interface{}
